services:
  wireguard.api:
    image: ${DOCKER_REGISTRY-}wireguardapi
    build:
      context: .
      dockerfile: wireguard.api/Dockerfile

  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
 